package com.elysium.softwork.worker.forum.domain.model

/**
 * A file attachment on a [Message] — the annotation-free bean for the `assets` **JSON**
 * responses (the *Bean / Pragmatic Shortcut*).
 *
 * The backend serializes JSON bodies in **uniform snake_case**, so every property here is
 * snake_case and Gson resolves each by reflection without `@SerializedName`. This bean models
 * the `AssetResponse` (and the JSON `PUT` update); the **creation** request is *not* JSON —
 * `POST /api/v1/assets` is `multipart/form-data`, whose form-field names stay camelCase
 * (`messageId`, `name`, `fileType`, `file`) and are declared on `ForumWebService.createAsset`,
 * not here. `url` and `file_size` are backend-computed after the Cloudinary upload.
 *
 * @property asset_id primary key returned by every asset response.
 * @property message_id parent message.
 * @property name file name.
 * @property url storage (Cloudinary) URL of the file, generated by the backend.
 * @property file_size size label, generated by the backend.
 * @property file_type type label (`VIDEO` / `JPEG` / `PDF`).
 * @property is_viewable response-only: whether the asset can be previewed inline.
 * @property is_readable response-only: whether the asset can be opened.
 */
data class Asset(
    val asset_id: Long? = null,
    val message_id: Long? = null,
    val name: String? = null,
    val url: String? = null,
    val file_size: String? = null,
    val file_type: String? = null,
    val is_viewable: Boolean? = null,
    val is_readable: Boolean? = null,
)
